services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - ENV=prod
      - POSTGRES_URL=postgres://postgres:postgres@database:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - HTTP_SERVER_ADDRESS=backend:8080
      - HTTP_SERVER_IDLE=4

  database:
    image: postgres:16
    container_name: database
    ports:
      - 2345:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./backend/dev/data/dump.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  database_data: