services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8080:800
    env_file:
      - ./backend/.env
    environment:
      - ENV=prod
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - HTTP_SERVER_ADDRESS="backend:8080"
      - HTTP_SERVER_IDLE=4

  database:
    image: postgres:16
    container_name: database
    ports:
      - 2345:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
